version: '3.4'


networks:
  backendNetwork:

services:
  app-db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@123456
    networks:
      - backendNetwork
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - app-db
    environment:
      - DB_HOST=app-db
      - DB_NAME=ExpenseManagerDB
      - DB_SA_PASSWORD=password@123456
    networks:
      - backendNetwork
    